[project]
name = "bespoke-resume-backend"
version = "0.1.0"
description = "FastAPI backend for resume tailoring"
dependencies = [
    "fastapi",
    "pydantic",
    "uvicorn",
    "mcp",
    "anthropic",
    "python-dotenv",
    "fastmcp>=2.10",
    "jinja2>=3.1",
    "pyyaml>=6.0"
]