[project]
name = "mcp-client"
version = "0.1.0"
description = "LaTeX client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.64.0",
    "fastapi>=0.116.1",
    "fastmcp>=2.11.3",
    "flask>=3.1.2",
    "mcp>=1.13.0",
    "python-dotenv>=1.1.1",
]
